"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 06:20:07.259463
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=40), nullable=False),
    sa.Column('emergency_status', sa.String(length=10), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hospital_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ambulances',
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('crew', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('destination_hospital_id', sa.Integer(), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.hospital_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ambulance_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('beds',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('bed_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('patient_name', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('hospital_id', 'code', name='uq_bed_hospital_code')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index('ix_bed_lookup', ['hospital_id', 'bed_type', 'status'], unique=False)

    op.create_table('capacity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('icu_usage', sa.Integer(), nullable=False),
    sa.Column('emergency_requests', sa.Integer(), nullable=False),
    sa.Column('icu_total', sa.Integer(), nullable=False),
    sa.Column('general_total', sa.Integer(), nullable=False),
    sa.Column('general_occupied', sa.Integer(), nullable=False),
    sa.Column('emergency_total', sa.Integer(), nullable=False),
    sa.Column('emergency_occupied', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capacity_history', schema=None) as batch_op:
        batch_op.create_index('ix_capacity_hospital_date', ['hospital_id', 'date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('medical_requirement', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('required_service', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.bed_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.create_index('ix_emergency_hospital_status', ['hospital_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_created_time'), ['created_time'], unique=False)

    op.create_table('referrals',
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('from_hospital', sa.Integer(), nullable=True),
    sa.Column('to_hospital', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('bed_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('ambulance_status', sa.String(length=30), nullable=True),
    sa.Column('pickup_location', sa.String(length=300), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.ambulance_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.bed_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_hospital'], ['hospitals.hospital_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_hospital'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('referral_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index('ix_referral_to_status', ['to_hospital', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_created_at'))
        batch_op.drop_index('ix_referral_to_status')

    op.drop_table('referrals')
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_requests_created_time'))
        batch_op.drop_index('ix_emergency_hospital_status')

    op.drop_table('emergency_requests')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_user_id'))

    op.drop_table('patients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('capacity_history', schema=None) as batch_op:
        batch_op.drop_index('ix_capacity_hospital_date')

    op.drop_table('capacity_history')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index('ix_bed_lookup')

    op.drop_table('beds')
    op.drop_table('ambulances')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
